src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\ApplicationRepository;
use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'date')]
    private $date;

    #[ORM\Column(type: 'integer')]
    private $seats;

    #[ORM\OneToMany(mappedBy: 'event', targetEntity: Application::class)]
    private $applications;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $title;

    public function __construct()
    {
        $this->applications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getSeats(): ?int
    {
        return $this->seats;
    }

    public function setSeats(int $seats): self
    {
        $this->seats = $seats;

        return $this;
    }

    /**
     * @return Collection|Application[]
     */
    public function getApplications(): Collection
    {
        return $this->applications;
    }

    public function getParticipants() {
        return $this->getApplicationsByStatus('accepted');
    }
    public function getPendingApplications() {
        return $this->getApplicationsByStatus('pending');
    }

    private function getApplicationsByStatus(string $status) {
        $applications = array_filter($this->getApplications()->toArray(), function($application) use ($status) {
            return $application->getStatus() === $status;
        });
        return array_map(function($application) {
            return $application->getUser();
        }, $applications);
    }

    public function addApplication(Application $application): self
    {
        if (!$this->applications->contains($application)) {
            $this->applications[] = $application;
            $application->setEvent($this);
        }

        return $this;
    }

    public function removeApplication(Application $application): self
    {
        if ($this->applications->removeElement($application)) {
            // set the owning side to null (unless already changed)
            if ($application->getEvent() === $this) {
                $application->setEvent(null);
            }
        }

        return $this;
    }

    public function getParticipantsCount() {
        return count($this->getParticipants());
    }
    public function getPendingApplicationsCount() {
        return count($this->getPendingApplications());
    }
    public function getApplicationsCount() {
        return count($this->getApplications());
    }

    public function getTitle(): ?string
    {
        if ($this->title) {
            return $this->title;
        }
        $date = $this->getDate() ?? new \DateTime();
        return 'Lundi ouistiti du ' . $date->format('d F Y');
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(EventRepository $repository): Response
    {
        $events = $repository->findNextEvents();
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'events' => $events
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les lundis ouistiti !{% endblock %}

{% block body %}
    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }
    </style>
    <div class="hero h-[600px]" style="background-image: url({{ asset('build/img/homebg.jpg') }});">
        <div class="hero-overlay bg-opacity-60"></div>
        <div class="text-center hero-content text-neutral-content">
            <div class="max-w-md">
                <h1 class="mb-5 text-5xl font-bold">{{ get_option('site_title') }}</h1>
                <p class="mb-5">{{ get_option('site_description') }}</p>
                <button class="btn btn-primary">Candidater</button>
            </div>
        </div>
    </div>
    <div class="container mx-auto my-16">

        {% for message in app.flashes('error') %}
            <div class="alert alert-error mb-2">
                <div class="flex-1">
                    {{ message }}
                </div>
            </div>
        {% endfor %}

        <h2 class="text-3xl font-bold">Les prochains événements</h2>
        <section class="flex flex-col gap-8 py-8">
            {% for event in events %}
                <div class="card w-full bg-base-100 shadow-2xl">
                    <div class="card-body flex-row">
                        <div class="flex flex-col flex-grow">
                            <h2 class="card-title">{{ event.title }}</h2>
                            <p>
                                {{ event.date|date('d M Y') }}
                            </p>
                            <h3 class="font-bold mt-2">Participants</h3>
                            <div class="avatar-group overflow-visible -space-x-4">
                                {% for user in event.participants %}
                                    <div class="avatar overflow-visible tooltip" data-tip="{{ user }}">
                                        <div class="w-8">
                                            <img src="{{ asset('build/img/avatar.svg') }}">
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>

                        </div>
                        <div class="justify-end card-actions">
                            <a href="{{ path('apply', {'event_id': event.id}) }}" class="btn btn-primary">Candidater</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </section>
    </div>
{% endblock %}